models/task.py
from utils.db import db


class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    userId = db.Column(db.Integer, nullable=False)
    description = db.Column(db.String(200), nullable=False)
    # status: new, in progress, done
    status = db.Column(db.String(15), nullable=False)

    def __init__(self, userId, description, status="new") -> None:
        self.userId = userId
        self.description = description
        self.status = status

    def __repr__(self) -> str:
        return f"Task({self.id}, {self.userId}, '{self.description}', '{self.status}')"

models/user.py
from utils.db import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), nullable=False, unique=True)
    password = db.Column(db.String(80), nullable=False)
    status = db.Column(db.String(20), nullable=False)
    rank = db.Column(db.String(20), nullable=False)

    def __init__(self, username, password, status, rank) -> None:
        self.username = username
        self.password = password
        self.status = status
        self.rank = rank

    def __repr__(self):
        return f"User({self.id}, '{self.username}', '{self.password}', '{self.status}', '{self.rank}')"

forms/loginForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Length, ValidationError
from models.user import User


class LoginForm(FlaskForm):
    username = StringField(
        validators=[
            InputRequired(),
            Length(min=4, max=20),
        ],
        render_kw={"placeholder": "username"},
    )

    password = PasswordField(
        validators=[
            InputRequired(),
            Length(min=4, max=20),
        ],
        render_kw={"placeholder": "password"},
    )

    submit = SubmitField("login")

forms/registerForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Length, ValidationError
from models.user import User


class RegisterForm(FlaskForm):
    username = StringField(
        validators=[
            InputRequired(),
            Length(min=4, max=20),
        ],
        render_kw={"placeholder": "username"},
    )

    password = PasswordField(
        validators=[
            InputRequired(),
            Length(min=4, max=20),
        ],
        render_kw={"placeholder": "password"},
    )

    submit = SubmitField("register")

    def validate_username(self, username):
        currentUser = User.query.filter_by(username=username).first()
        if currentUser:
            raise ValidationError("the username already exists")

forms/taskCreateForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Length, ValidationError


class TaskCreateForm(FlaskForm):
    description = StringField(
        validators=[
            InputRequired(),
            Length(min=1, max=200),
        ],
        render_kw={"placeholder": "description"},
    )

    submit = SubmitField("create task")

app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from routes.auth import auth
from routes.todolist import todolist
from flask_bcrypt import Bcrypt
from flask_migrate import Migrate
from utils.loginManagerService import login_manager
from utils.db import db

app = Flask(__name__)

app.config.from_object("config.BaseConfig")

SQLAlchemy(app)
Bcrypt(app)
login_manager.init_app(app)
Migrate(app, db)

app.register_blueprint(auth)
app.register_blueprint(todolist)

routes/auth.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user
from forms.registerForm import RegisterForm
from forms.loginForm import LoginForm
from utils.bcryptService import bcrypt
from models.user import User
from utils.db import db

auth = Blueprint("auth", __name__)


@auth.route("/")
def home():
    return render_template("home.html")


@auth.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        currentUser = User.query.filter_by(username=username).first()
        if currentUser:
            if bcrypt.check_password_hash(currentUser.password, password):
                login_user(currentUser)
                return redirect(url_for("todolist.home"))
    return render_template("login.html", form=form)


@auth.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        hashed_password = bcrypt.generate_password_hash(password)
        newUser = User(username, hashed_password, "active", "user")
        db.session.add(newUser)
        db.session.commit()
        return redirect(url_for("auth.login"))
    return render_template("register.html", form=form)


@auth.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("auth.login"))


@auth.route("/dashboard")
@login_required
def dashboard():
    print(f"current_user: {current_user}")
    return render_template("dashboard.html", user=current_user)

routes/todolist.py
from flask import Blueprint, render_template
from flask_login import current_user, login_required
from forms.taskCreateForm import TaskCreateForm
from models.user import User
from models.task import Task

todolist = Blueprint("todolist", __name__, url_prefix="/todolist")


@todolist.route("/")
@login_required
def home():
    userList = None
    if "admin" in current_user.rank:
        # es un admin
        userList = User.query.all()
    else:
        # es un user
        userList = list((User.query.filter_by(id=current_user.id).first(),))
    return render_template("todolist/home.html", user=current_user, userList=userList)


@todolist.route("/tasklist/<int:userId>")
@login_required
def tasklist(userId):
    currentTaskList = Task.query.filter_by(userId=userId).all()
    return render_template("todolist/tasklist.html", user=current_user, userId=userId, tasks=currentTaskList)


@todolist.route("/tasklist/create/<int:userId>", methods=["GET", "POST"])
@login_required
def create(userId):
    form = TaskCreateForm()
    if form.validate_on_submit():
        pass
    return render_template("todolist/create.html", form=form, user=current_user, userId=userId)

templates/home.html
{% extends 'layout.html' %}
{% block title %}todolist webapp{% endblock %}
{% block contents %}
<h1>todolist webapp</h1>
<br>
<a href="{{ url_for('auth.login') }}">login</a><br>
<a href="{{ url_for('auth.register') }}">register</a>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    {% block contents %}{% endblock %}
</body>

</html>

templates/login.html
{% extends 'layout.html' %}
{% block title %}login page{% endblock %}
{% block contents %}
<h1>login page</h1>
<br>
<form action="{{ url_for('auth.login') }}" method="post">
    {{ form.hidden_tag() }}
    {{ form.username.label }}
    {{ form.username }}
    {{ form.password.label }}
    {{ form.password }}
    {{ form.submit }}
</form>
<br>
<a href="{{ url_for('auth.register') }}">register</a>
{% endblock %}

templates/register.html
{% extends 'layout.html' %}
{% block title %}register page{% endblock %}
{% block contents %}
<h1>register page</h1>
<br>
<form action="{{ url_for('auth.register') }}" method="post">
    {{ form.hidden_tag() }}
    {{ form.username.label }}
    {{ form.username }}
    {{ form.password.label }}
    {{ form.password }}
    {{ form.submit }}
</form>
<br>
<a href="{{ url_for('auth.login') }}">login</a>
{% endblock %}

templates/todolist/create.html
{% extends 'layout.html' %}
{% block title %}task create{% endblock %}
{% block contents %}
<h1>task create</h1>
<br>
{% if user %}
<p>Hello, {{user.username}} rank: {{user.rank}}</p>
<br>
<a href="{{ url_for('auth.logout') }}">logout</a>
{% endif %}
<p>task create</p>
<br>
<form action="#" method="post">
    {{ form.hidden_tag() }}
    {{ form.description.label }}
    {{ form.description }}
    {{ form.submit }}
</form>

{% endblock %}

templates/todolist/home.html
{% extends 'layout.html' %}
{% block title %}todolist home{% endblock %}
{% block contents %}
<h1>todolist home</h1>
<br>
{% if user %}
<p>Hello, {{user.username}} rank: {{user.rank}}</p>
<br>
<a href="{{ url_for('auth.logout') }}">logout</a>
{% endif %}
<p>this is my awesome todolist home</p>

{% for userItem in userList %}
<a href="{{ url_for('todolist.tasklist', userId=userItem.id) }}">{{ userItem.username }}</a><br>
{% endfor %}

{% endblock %}

templates/todolist/tasklist.html
{% extends 'layout.html' %}
{% block title %}tasklist{% endblock %}
{% block contents %}
<h1>tasklist</h1>
<br>
{% if user %}
<p>Hello, {{user.username}} rank: {{user.rank}}</p>
<br>
<a href="{{ url_for('auth.logout') }}">logout</a>
{% endif %}
<p>tasklist of user</p>
<br>
<a href="{{ url_for('todolist.create', userId=userId) }}">create a task</a>
<br>
{% endblock %}